/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.BanVe;


import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.TuyenTau;
import service.BanVeService;

/**
 *
 * @author Luc
 */
public class BanVe extends javax.swing.JFrame {
    BanVeService banveService;
    DefaultTableModel defaultTableModel;
    List<TuyenTau> tuyenTau = new ArrayList<TuyenTau>();
    
    /**
     * Creates new form BanVe
     */
    public BanVe(String TenTuyen) {
        initComponents();
        banveService = new BanVeService();
        this.setLocationRelativeTo(null);
         defaultTableModel = new DefaultTableModel(){    
            @Override
            public boolean isCellEditable(int row, int column){
            return false;
            }
        };
      
        ChonTuyenTable.setModel(defaultTableModel);
        defaultTableModel.addColumn("Mã Tuyến");
        defaultTableModel.addColumn("Tên Tuyến");
        defaultTableModel.addColumn("Thời Gian Bắt Đầu");
        defaultTableModel.addColumn("Thời Gian Kết Thúc");
        defaultTableModel.addColumn("Loại Tuyến");
        defaultTableModel.addColumn("Giá Tuyến");
        defaultTableModel.addColumn("Thời Gian Chờ");
             
        setTableData(banveService.getTuyenTauByTenGa(TenTuyen));
    }
    
    private void setTableData(List<TuyenTau> tuyenTau){
        for (TuyenTau tuyentau : tuyenTau){
            defaultTableModel.addRow(new Object[]{tuyentau.getMaTT(), tuyentau.getTenTT(), 
               tuyentau.getTGbatdau(), tuyentau.getTGkethuc(), tuyentau.getLoaiTuyen(), tuyentau.getGiaTuyen(), 
               tuyentau.getTGcho()});
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ChonTuyenTable = new javax.swing.JTable();
        btnChonTuyen = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EMETRO - TRANG CHỌN TUYẾN");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(52, 152, 219));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CHỌN TUYẾN TÀU");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 66));

        ChonTuyenTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Tuyến ", "Tên Tuyến", "Thời Gian Bắt Đầu", "Thời Gian Kết Thúc", "Loại Tuyến ", "Giá Tuyến", "Thời Gian Chờ", "Mã Ga Đi", "Mã Ga Đến"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ChonTuyenTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 145, 1000, 320));

        btnChonTuyen.setBackground(new java.awt.Color(52, 152, 219));
        btnChonTuyen.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnChonTuyen.setForeground(new java.awt.Color(255, 255, 255));
        btnChonTuyen.setText("Chọn");
        btnChonTuyen.setBorderPainted(false);
        btnChonTuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonTuyenActionPerformed(evt);
            }
        });
        getContentPane().add(btnChonTuyen, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 520, -1, -1));

        btnRefresh.setBackground(new java.awt.Color(52, 152, 219));
        btnRefresh.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("Refresh");
        btnRefresh.setBorderPainted(false);
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/emetro13.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChonTuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonTuyenActionPerformed
        int row = ChonTuyenTable.getSelectedRow();
        if(row == -1){
            JOptionPane.showMessageDialog(BanVe.this, "Vui lòng chọn tuyến tàu muốn đi", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            String MaTuyen = String.valueOf(ChonTuyenTable.getValueAt(row, 0));
             
             Ve ve = new Ve(MaTuyen);
             ve.setVisible(true);
             this.dispose();
        }       
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChonTuyenActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
       defaultTableModel.setRowCount(0);
       setTableData(banveService.getAllTuyenTau());     
    }//GEN-LAST:event_btnRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ChonTuyenTable;
    private javax.swing.JButton btnChonTuyen;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    
}
