/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.BanVe;


import controller.ConnectionSQLServer;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import java.sql.Connection;
import model.Ga;
import model.TuyenTau;
import service.BanVeService;
import view.DangNhap.TrangChonBV;


/**
 *
 * @author Luc
 */
public class ChonGa extends javax.swing.JFrame {
    Ga ga;   
    BanVeService banveService = new BanVeService();  
    List<TuyenTau> tuyenTau = new ArrayList<TuyenTau>();
   /**
     * Creates new form ChonGa
     */
    public ChonGa() {
        initComponents();
        ChonGaDi();
        ChonGaDen();       
        this.setLocationRelativeTo(null);
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbGaDi = new javax.swing.JComboBox<>();
        jcbGaDen = new javax.swing.JComboBox<>();
        btnChonGa = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EMETRO - TRANG CHỌN GA");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(52, 152, 219));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CHỌN GA");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 66));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(52, 152, 219));
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("  Chọn Ga Đi");
        jLabel1.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(52, 152, 219));
        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(" Chọn Ga Đến");
        jLabel2.setOpaque(true);

        jcbGaDi.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jcbGaDi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn Ga Đi" }));
        jcbGaDi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbGaDiActionPerformed(evt);
            }
        });

        jcbGaDen.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jcbGaDen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn Ga Đến" }));
        jcbGaDen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbGaDenActionPerformed(evt);
            }
        });

        btnChonGa.setBackground(new java.awt.Color(52, 152, 219));
        btnChonGa.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnChonGa.setForeground(new java.awt.Color(255, 255, 255));
        btnChonGa.setText("Tiếp Theo");
        btnChonGa.setBorderPainted(false);
        btnChonGa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonGaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jcbGaDi, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(jcbGaDen, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(btnChonGa)))
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbGaDi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbGaDen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(btnChonGa))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 188, 400, 300));

        btnBack.setBackground(new java.awt.Color(52, 152, 219));
        btnBack.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("TRỞ VỀ");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/emetro12.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChonGaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonGaActionPerformed
        String TenGaDi = (String) jcbGaDi.getSelectedItem();
        String TenGaDen = (String) jcbGaDen.getSelectedItem();
        String TenTuyen = TenGaDi+" - "+TenGaDen; 
        new BanVe(TenTuyen).setVisible(true);
        this.dispose();       
    }//GEN-LAST:event_btnChonGaActionPerformed

    private void jcbGaDenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbGaDenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbGaDenActionPerformed

    private void jcbGaDiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbGaDiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbGaDiActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new TrangChonBV().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

 public void ChonGaDi(){
        try {
            Connection connection =  ConnectionSQLServer.getConnectionDB();
        
            String sql = "SELECT DISTINCT TEN_GA,TUYEN_TAU.MA_GA_XUAT_PHAT FROM GA,TUYEN_TAU WHERE TUYEN_TAU.MA_GA_XUAT_PHAT = GA.MA_GA"; 
        
            PreparedStatement preparedStatement = connection.prepareStatement(sql);
        
            ResultSet rs = preparedStatement.executeQuery();
                while(rs.next())
                {                                        
                    jcbGaDi.addItem(rs.getString("TEN_GA"));
                }
            }catch(Exception e){
             e.printStackTrace();
            }
    }
 
 public void ChonGaDen(){
        try {
            Connection connection =  ConnectionSQLServer.getConnectionDB();
        
            String sql = "SELECT DISTINCT TEN_GA,TUYEN_TAU.MA_GA_KET_THUC FROM GA,TUYEN_TAU WHERE TUYEN_TAU.MA_GA_KET_THUC = GA.MA_GA"; 
        
            PreparedStatement preparedStatement = connection.prepareStatement(sql);
        
            ResultSet rs = preparedStatement.executeQuery();
                while(rs.next())
                {                 
                    jcbGaDen.addItem(rs.getString("TEN_GA"));
                }
            }catch(Exception e){
                e.printStackTrace();
            }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnChonGa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> jcbGaDen;
    private javax.swing.JComboBox<String> jcbGaDi;
    // End of variables declaration//GEN-END:variables
}
