/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.BanVe;

import com.itextpdf.text.Document;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.sql.Date;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import model.ThongTinVe;
import model.TuyenTau;
import service.BanVeService;


/**
 *
 * @author Luc
 */
public class HoaDon extends javax.swing.JFrame {
    ThongTinVe thongtinve;
    TuyenTau tuyentau;
    BanVeService banveService;
    String CMND;
    String tenKH;
    String SDT;
    String tenTuyen;
    String thoiGianDi;
    /**
     * Creates new form HoaDon
     */
    public HoaDon(String mave, String makh, String tenkh, String sdt, String loaive, String loaidt,String cmnd,String thoigiandi,String tentuyen) {
        initComponents();
        this.setLocationRelativeTo(null);
        thongtinve = new ThongTinVe();
        tuyentau = new TuyenTau();
        banveService = new BanVeService();
     
        txtMaVe.setText(mave);
        txtMaKH.setText(makh);
        txtTenKH.setText(tenkh);
        txtSDT.setText(sdt);
        txtLoaiVe.setText(loaive);
        txtLoaiKH.setText(loaidt);
        CMND = cmnd;
        tenKH = tenkh;
        SDT=sdt;
        thoiGianDi = thoigiandi;
        tenTuyen = tentuyen;
        
        txtTongTien.setText(banveService.getTriGiaByMaVe(mave));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnThanhToan = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        btnInVe = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtMaKH = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTenKH = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMaVe = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtLoaiKH = new javax.swing.JTextField();
        txtLoaiVe = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EMETRO - TRANG HOÁ ĐƠN");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(52, 152, 219));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HOÁ ĐƠN");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 833, 66));

        btnThanhToan.setBackground(new java.awt.Color(52, 152, 219));
        btnThanhToan.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnThanhToan.setForeground(new java.awt.Color(255, 255, 255));
        btnThanhToan.setText("Thanh Toán");
        btnThanhToan.setBorderPainted(false);
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });
        getContentPane().add(btnThanhToan, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 584, -1, -1));

        btnHuy.setBackground(new java.awt.Color(52, 152, 219));
        btnHuy.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setText("Huỷ Vé");
        btnHuy.setBorderPainted(false);
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });
        getContentPane().add(btnHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 584, 130, -1));

        btnInVe.setBackground(new java.awt.Color(52, 152, 219));
        btnInVe.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnInVe.setForeground(new java.awt.Color(255, 255, 255));
        btnInVe.setText("In Vé");
        btnInVe.setBorderPainted(false);
        btnInVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInVeActionPerformed(evt);
            }
        });
        getContentPane().add(btnInVe, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 584, 149, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtMaKH.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Tên Khách Hàng");

        txtTenKH.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Mã Vé");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("SDT");

        txtMaVe.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        txtSDT.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Đối Tượng");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Loại Vé");

        txtLoaiKH.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtLoaiKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoaiKHActionPerformed(evt);
            }
        });

        txtLoaiVe.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Mã Khách Hàng");

        txtTongTien.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Tổng Tiền");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addGap(83, 83, 83)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTongTien)
                    .addComponent(txtMaVe)
                    .addComponent(txtLoaiVe)
                    .addComponent(txtLoaiKH)
                    .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenKH)
                    .addComponent(txtSDT))
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtMaVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLoaiVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLoaiKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 122, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/emetro15.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 830, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
              
        String loaive = txtLoaiVe.getText();
        
        if("Vé Thường".equals(loaive)){
            
            thongtinve.setMaVe(txtMaVe.getText());
            thongtinve.setThoiDiemDungVe(null);
            thongtinve.setTinhTrangVe("Chưa sử dụng");
            thongtinve.setMaKhachHang(txtMaKH.getText());
            
            banveService.ThemVeThuong(thongtinve);
        }
        if("Vé Tháng".equals(loaive)){
            
            thongtinve.setMaVe(txtMaVe.getText());
            thongtinve.setSoLanSD(0);
            thongtinve.setTinhTrangVe("Còn hạn");
            thongtinve.setNgayMua(Date.valueOf(LocalDate.now()));
            thongtinve.setNgayKetThuc(null);
            thongtinve.setMaKhachHang(txtMaKH.getText());
            
            banveService.ThemVeThang(thongtinve);
        }
        JOptionPane.showMessageDialog(rootPane,"Thanh Toán Thành Công!");  
        
        
        
    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
       String MaVe = txtMaVe.getText();
       String MaKH = txtMaKH.getText();
       banveService.HuyVe(MaVe);
       banveService.HuyKH(MaKH);
       
        this.dispose();
        ChonGa chonga= new ChonGa();
        chonga.setVisible(true);
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnInVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInVeActionPerformed

        try {

            String file_name= "C:\\Users\\nampr\\Desktop\\HoaDon.pdf";
            Document document = new Document() ;
            PdfWriter.getInstance(document, new FileOutputStream(file_name));
            document.open();
            PdfPTable table= new PdfPTable(6);        
           
            PdfPCell c1 = new PdfPCell(new Phrase("TEN KHACH HANG"));
            document.newPage();
            table.addCell(c1);
            c1 = new PdfPCell(new Phrase("SDT"));
            table.addCell(c1);
            c1 = new PdfPCell(new Phrase("MA VE"));
            table.addCell(c1);
            c1 = new PdfPCell(new Phrase("LOAI VE"));
            table.addCell(c1);
            c1 = new PdfPCell(new Phrase("TEN TUYEN"));
            table.addCell(c1);
            c1 = new PdfPCell(new Phrase("NGAY MUA"));
            table.addCell(c1);

            table.addCell(tenKH);
            table.addCell(SDT);
            table.addCell(txtMaVe.getText());
            table.addCell(txtLoaiVe.getText());
            table.addCell(tenTuyen);
            table.addCell(String.valueOf((LocalDate.now())));

            document.add(table);

            document.close();
            
        } catch (Exception e) {
            System.err.println(e);
        }
        JOptionPane.showMessageDialog(rootPane, "In vé thành công!");
        this.dispose();
        ChonGa chonga = new ChonGa();
        chonga.setVisible(true);
    }//GEN-LAST:event_btnInVeActionPerformed

    private void txtSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDTActionPerformed

    private void txtLoaiKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoaiKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoaiKHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnInVe;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtLoaiKH;
    private javax.swing.JTextField txtLoaiVe;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtMaVe;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
}
