/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.DangNhap;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import view.BanVe.ChonGa;
import view.Ga.TrangQLGa;
import view.TuyenTau.TrangQLTT;

/**
 *
 * @author nampr
 */
public class TrangDangNhap extends javax.swing.JFrame {
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form DangNhap
     */
    public TrangDangNhap() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTedn = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        btnDN = new javax.swing.JButton();
        cbbLoai = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EMETRO - TRANG ĐĂNG NHẬP");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 30, 40));

        jLabel2.setBackground(new java.awt.Color(52, 152, 219));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ĐĂNG NHẬP");
        jLabel2.setOpaque(true);
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 66));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("TÊN ĐĂNG NHẬP:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 96, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("MẬT KHẨU:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 173, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("LOẠI NHÂN VIÊN:");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 260, -1, -1));

        txtTedn.setBackground(new java.awt.Color(255, 255, 255));
        txtTedn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtTedn.setForeground(new java.awt.Color(0, 0, 0));
        txtTedn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(52, 152, 219), new java.awt.Color(52, 152, 219), new java.awt.Color(52, 152, 219), new java.awt.Color(52, 152, 219)));
        txtTedn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTednActionPerformed(evt);
            }
        });
        txtTedn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTednKeyPressed(evt);
            }
        });
        jPanel4.add(txtTedn, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 87, 300, 42));

        txtPass.setBackground(new java.awt.Color(255, 255, 255));
        txtPass.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtPass.setForeground(new java.awt.Color(0, 0, 0));
        txtPass.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(52, 152, 219), new java.awt.Color(52, 152, 219), new java.awt.Color(52, 152, 219), new java.awt.Color(52, 152, 219)));
        jPanel4.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 167, 300, 42));

        btnDN.setBackground(new java.awt.Color(52, 152, 219));
        btnDN.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnDN.setForeground(new java.awt.Color(255, 255, 255));
        btnDN.setText("ĐĂNG NHẬP");
        btnDN.setBorder(null);
        btnDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDNActionPerformed(evt);
            }
        });
        btnDN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnDNKeyPressed(evt);
            }
        });
        jPanel4.add(btnDN, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 327, 355, 59));

        cbbLoai.setBackground(new java.awt.Color(255, 255, 255));
        cbbLoai.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cbbLoai.setForeground(new java.awt.Color(0, 0, 0));
        cbbLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHỌN LOẠI NHÂN VIÊN", "NHÂN VIÊN SỞ GTTP", "NHÂN VIÊN CÔNG TY", "NHÂN VIÊN BÁN VÉ" }));
        cbbLoai.setToolTipText("");
        cbbLoai.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(52, 152, 219), new java.awt.Color(52, 152, 219), new java.awt.Color(52, 152, 219), new java.awt.Color(52, 152, 219)));
        cbbLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbLoaiActionPerformed(evt);
            }
        });
        jPanel4.add(cbbLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 251, 300, 42));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 540, 410));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/emetro_img.jpg"))); // NOI18N
        jLabel9.setToolTipText("");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTednActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTednActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTednActionPerformed

    private void txtTednKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTednKeyPressed

    }//GEN-LAST:event_txtTednKeyPressed

    private void btnDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDNActionPerformed
        String uname = txtTedn.getText();
        String upass = String.valueOf(txtPass.getPassword());
        String uloai = (String) cbbLoai.getSelectedItem();
        try {
            String URL = "jdbc:sqlserver://localhost:1433;databaseName=EMETRO";
            String user = "sa";
            String password = "sa";
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            con = DriverManager.getConnection(URL, user, password);
            System.out.println("Kết nối thành công");

            String sql = "select * from nhan_vien WHERE TAI_KHOAN = ? AND MAT_KHAU = ? AND LOAI_NV = ?";

            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, uname);
            pst.setString(2, upass);
            pst.setString(3, uloai);

            rs = pst.executeQuery();
            
            if(rs.next()){
                if(uloai == "NHÂN VIÊN CÔNG TY"){
                    JOptionPane.showMessageDialog(TrangDangNhap.this, "Đăng nhập thành công!");
                    String MaCTy = rs.getString("MA_CTY");
                    System.out.println(MaCTy);
                    new TrangQLTT(MaCTy).setVisible(true);
                    this.dispose();
                }
                if(uloai == "NHÂN VIÊN SỞ GTTP"){
                    JOptionPane.showMessageDialog(TrangDangNhap.this, "Đăng nhập thành công!");
                    new TrangChonQL().setVisible(true);
                    this.dispose();
                }
                if(uloai == "NHÂN VIÊN BÁN VÉ"){
                    JOptionPane.showMessageDialog(TrangDangNhap.this, "Đăng nhập thành công!");
                    new TrangChonBV().setVisible(true);
                    this.dispose();
                }
            } else{
                JOptionPane.showMessageDialog(TrangDangNhap.this, "Sai tên đăng nhập - mật khẩu hoặc loại nhân viên!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }

        }catch(Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnDNActionPerformed

    private void btnDNKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnDNKeyPressed
        // TODO add your handling code here:
        int key=evt.getKeyCode();
        if(key == 10){
            String uname = txtTedn.getText();
            String upass = String.valueOf(txtPass.getPassword());
            String uloai = (String) cbbLoai.getSelectedItem();
            try {
                String URL = "jdbc:sqlserver://localhost:1433;databaseName=EMETRO";
                String user = "sa";
                String password = "sa";
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                con = DriverManager.getConnection(URL, user, password);
                System.out.println("Kết nối thành công");

                String sql = "select * from nhan_vien WHERE TAI_KHOAN = ? AND MAT_KHAU = ?";

                PreparedStatement pst = con.prepareStatement(sql);
                pst.setString(1, uname);
                pst.setString(2, upass);

                rs = pst.executeQuery();
                
                if(rs.next()){
                    if(uloai == "NHÂN VIÊN CÔNG TY"){
                        JOptionPane.showMessageDialog(TrangDangNhap.this, "Đăng nhập thành công!");
                        String MaCTy = rs.getString("MA_CTY");
                        System.out.println(MaCTy);
                        new TrangQLTT(MaCTy).setVisible(true);
                        this.dispose();
                    }
                    if(uloai == "NHÂN VIÊN SỞ GTTP"){
                        JOptionPane.showMessageDialog(TrangDangNhap.this, "Đăng nhập thành công!");
                        new TrangChonQL().setVisible(true);
                        this.dispose();
                    }
                    if(uloai == "NHÂN VIÊN BÁN VÉ"){
                        JOptionPane.showMessageDialog(TrangDangNhap.this, "Đăng nhập thành công!");
                        new TrangChonBV().setVisible(true);
                        this.dispose();
                    }
                } else{
                    JOptionPane.showMessageDialog(TrangDangNhap.this, "Sai tên đăng nhập - mật khẩu hoặc loại nhân viên!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                }

            }catch(Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnDNKeyPressed

    private void cbbLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbLoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbLoaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDN;
    private javax.swing.JComboBox<String> cbbLoai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtTedn;
    // End of variables declaration//GEN-END:variables
}
