/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.TKBC;


import com.itextpdf.text.Document;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import controller.ConnectionSQLServer;
import java.io.FileOutputStream;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.TKBC;
import service.TKBCService;
import view.DangNhap.TrangChonBV;

/**
 *
 * @author DELL
 */
public class ThongKeBaoCao extends javax.swing.JFrame {
    Connection cn = null;
    ResultSet rs = null;
    CallableStatement stored_pro = null;  
    private List<TKBC> tkbcs; 
    private TKBC tkbc;
    DefaultTableModel tblmodel ;
    TKBCService tkbcService; 
    private void setTableData(List<TKBC> tkbcs) { 
      for ( TKBC tkbc : tkbcs){
            tblmodel.addRow(new Object[]{tkbc.getMaVe(),tkbc.getTriGia(),
           tkbc.getMaTuyen(), tkbc.getNgayMua(), tkbc.getMaKM(), tkbc.getMaKH(),
           tkbc.getMaNV(), tkbc.getLoaiVe()});
        }
    }    

    public void TinhTongDT(TKBC tkbc){
        try {
            
            double tongdt = 0.0;
         
            cn = ConnectionSQLServer.getConnectionDB();
            stored_pro = cn.prepareCall("{call PROC_TONG_DT(?, ?, ?, ?)}");
            stored_pro.setString(1, txtMaBC.getText());
            stored_pro.setString(2, txtNgayBD.getText());
            stored_pro.setString(3, txtNgayKT.getText());
            stored_pro.setDouble(4, tongdt);
            rs = stored_pro.executeQuery();
            System.out.println(rs);
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "OK!");
                rs.close();
                stored_pro.close();
                cn.close(); 
            }
        } catch (Exception e) {
        }
    }
        
    public void LayTongDT(){
    
    try {
            cn = ConnectionSQLServer.getConnectionDB();
            String sql = "SELECT TONG_DOANH_THU FROM BAO_CAO WHERE MA_BC = ?";
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.setString(1, txtMaBC.getText());
            rs = pst.executeQuery();

            if(rs.next()){
                 
               JlbSum.setText("Tổng doanh thu: "+" "+ rs.getString("TONG_DOANH_THU")+" "+"VND" ); 
            }
           
        } catch (Exception e) {
        }
         
    }
    
    public void TinhDoanhThu(){
        double sum = 0.0;
        try {
            cn = ConnectionSQLServer.getConnectionDB();
            stored_pro = cn.prepareCall("{call PROC_TONG_DT(?, ?, ?, ?)}");
            stored_pro.setString(1, txtMaBC.getText());
            stored_pro.setString(2, txtNgayBD.getText());
            stored_pro.setString(3, txtNgayKT.getText());
            stored_pro.setDouble(4, sum);
            rs = stored_pro.executeQuery();
            System.out.println(rs);
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "OK!");
                rs.close();
                stored_pro.close();
                cn.close(); 
            }
        } catch (Exception e) {
        }
    }
    

    public ThongKeBaoCao() {
        initComponents();
        this.setLocationRelativeTo(null);
        tkbcService = new TKBCService();
        tkbc = new TKBC();
        tblmodel = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        
        tblTK.setModel(tblmodel);
        
        tblmodel.addColumn("Mã vé");
        tblmodel.addColumn("Trị giá");
        tblmodel.addColumn("Mã tuyến");
        tblmodel.addColumn("Ngày mua");
        tblmodel.addColumn("Mã KM");
        tblmodel.addColumn("Mã KH");
        tblmodel.addColumn("Mã NV");
        tblmodel.addColumn("Loại vé");
        
        setTableData(tkbcService.getAll());
        
        lbNgaylap.setText("Ngày lập báo cáo:"+" "+java.time.LocalDate.now());
                 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTK = new javax.swing.JTable();
        btnSum = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNgayBD = new javax.swing.JTextField();
        txtNgayKT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JlbSum = new javax.swing.JLabel();
        btnTK = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbNgaylap = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMaBC = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtND = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnPDF = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BẢNG THỐNG KÊ");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblTK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã vé", "Trị giá", "Mã tuyến", "Ngày mua", "Mã KM", "Mã KH", "Mã NV", "Loại vé"
            }
        ));
        jScrollPane1.setViewportView(tblTK);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 769, 260));

        btnSum.setBackground(new java.awt.Color(52, 152, 219));
        btnSum.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnSum.setForeground(new java.awt.Color(255, 255, 255));
        btnSum.setText("TỔNG DOANH THU");
        btnSum.setBorderPainted(false);
        btnSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumActionPerformed(evt);
            }
        });
        getContentPane().add(btnSum, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 740, -1, -1));

        jLabel3.setBackground(new java.awt.Color(52, 152, 219));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("NHẬP THÔNG TIN THỐNG KÊ");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 66));

        jLabel1.setBackground(new java.awt.Color(52, 152, 219));
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("  Ngày kết thúc");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 130, 30));

        txtNgayBD.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtNgayBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayBDActionPerformed(evt);
            }
        });
        getContentPane().add(txtNgayBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 190, 192, 40));

        txtNgayKT.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtNgayKT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayKTActionPerformed(evt);
            }
        });
        getContentPane().add(txtNgayKT, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 260, 192, 40));

        jLabel4.setBackground(new java.awt.Color(52, 152, 219));
        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("  Ngày bắt đầu");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 130, 30));

        JlbSum.setBackground(new java.awt.Color(255, 255, 255));
        JlbSum.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        JlbSum.setForeground(new java.awt.Color(52, 152, 219));
        JlbSum.setOpaque(true);
        getContentPane().add(JlbSum, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 740, 270, 40));

        btnTK.setBackground(new java.awt.Color(52, 152, 219));
        btnTK.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnTK.setForeground(new java.awt.Color(255, 255, 255));
        btnTK.setText("THỐNG KÊ");
        btnTK.setBorderPainted(false);
        btnTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTKActionPerformed(evt);
            }
        });
        getContentPane().add(btnTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 350, -1, -1));

        btnExit.setBackground(new java.awt.Color(52, 152, 219));
        btnExit.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("THOÁT");
        btnExit.setBorderPainted(false);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 740, 120, -1));

        jLabel2.setBackground(new java.awt.Color(52, 152, 219));
        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("(YYYY-MM-DD)");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, 130, 20));

        lbNgaylap.setBackground(new java.awt.Color(255, 255, 255));
        lbNgaylap.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbNgaylap.setForeground(new java.awt.Color(52, 152, 219));
        lbNgaylap.setOpaque(true);
        getContentPane().add(lbNgaylap, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 352, 40));

        jLabel5.setBackground(new java.awt.Color(52, 152, 219));
        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("(YYYY-MM-DD)");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, -1, 20));

        txtMaBC.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtMaBC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaBCActionPerformed(evt);
            }
        });
        getContentPane().add(txtMaBC, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 184, 40));

        jLabel6.setBackground(new java.awt.Color(52, 152, 219));
        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("  Mã báo cáo");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 130, 40));

        txtMaNV.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(txtMaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 184, 40));

        jLabel7.setBackground(new java.awt.Color(52, 152, 219));
        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("  Mã nhân viên");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 130, 40));

        txtND.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(txtND, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 184, 40));

        jLabel8.setBackground(new java.awt.Color(52, 152, 219));
        jLabel8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("  Nội dung");
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 130, 40));

        btnPDF.setBackground(new java.awt.Color(52, 152, 219));
        btnPDF.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnPDF.setForeground(new java.awt.Color(255, 255, 255));
        btnPDF.setText("XUẤT PDF");
        btnPDF.setBorderPainted(false);
        btnPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDFActionPerformed(evt);
            }
        });
        getContentPane().add(btnPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 110, 160, -1));

        btnBack.setBackground(new java.awt.Color(52, 152, 219));
        btnBack.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("TRỞ VỀ");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 740, -1, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/emetro16.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1040, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSumActionPerformed

    private void txtNgayKTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayKTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayKTActionPerformed

    private void btnTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTKActionPerformed
       String NgayBD= txtNgayBD.getText();
       String NgayKT= txtNgayKT.getText();
       
       tkbc.setMaNV(txtMaNV.getText());
       tkbc.setMaBC(txtMaBC.getText());
       tkbc.setNoiDung(txtND.getText());
       tkbc.setNgayBD(txtNgayBD.getText());
       tkbc.setNgayKT(txtNgayKT.getText());
       tkbcService.addBC(tkbc);
       TinhTongDT(tkbc);
       LayTongDT(); 
       
        if ((NgayBD.length()>0) && (NgayKT.length()>0)) {
           tkbcs = tkbcService.getTT(NgayBD, NgayKT);
           tblmodel.setRowCount(0);
           setTableData(tkbcs);
    }
       
        
       
       double sum=0;
        for (int i=0; i < tblTK.getRowCount(); i ++) {
            sum +=Double.parseDouble(tblTK.getValueAt(i,1).toString());
        }
       
       tkbc.setTongDoanhThu(sum);
        
             
       txtNgayBD.setText("");
       txtNgayKT.setText("");
       txtMaBC.setText("");
       txtMaNV.setText("");
       txtND.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_btnTKActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
            // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFActionPerformed
        try {
            
            String file_name= "C:\\Users\\nampr\\Desktop\\TKBC.pdf";
            Document document = new Document();
            PdfWriter.getInstance(document, new FileOutputStream(file_name));
            document.open();
            
            PdfPTable table= new PdfPTable(7);
            PdfPCell c1 = new PdfPCell(new Phrase("MA_BC"));
            document.newPage();
            table.addCell(c1);
            c1 = new PdfPCell(new Phrase("NGAY_LAP"));
            table.addCell(c1);
            c1 = new PdfPCell(new Phrase("NGAY_BD"));
            table.addCell(c1);
            c1 = new PdfPCell(new Phrase("NGAY_KT"));
            table.addCell(c1);
            c1 = new PdfPCell(new Phrase("NOI_DUNG"));
            table.addCell(c1);
            c1 = new PdfPCell(new Phrase("TONG_DOANH_THU"));
            table.addCell(c1);
            c1 = new PdfPCell(new Phrase("MA_NV"));
            table.addCell(c1);
           /* table.setHeaderRows(1); */
            
            table.addCell(tkbc.getMaBC());
            table.addCell(String.valueOf(LocalDate.now()));
            table.addCell(tkbc.getNgayBD());
            table.addCell(tkbc.getNgayKT());
            table.addCell(tkbc.getNoiDung());
            table.addCell(String.valueOf(tkbc.getTongDoanhThu()));
            table.addCell(tkbc.getMaNV());
            
            document.add(table);
            
            document.close();
        } catch (Exception e) {
            System.err.println(e);
        }
        
        JlbSum.setText("");
        JOptionPane.showMessageDialog(rootPane, "Xuất file thành công!");
        this.dispose();
        ThongKeBaoCao tkbc = new ThongKeBaoCao();
        tkbc.setVisible(true);
         
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPDFActionPerformed

    private void txtMaBCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaBCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaBCActionPerformed

    private void txtNgayBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayBDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayBDActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new TrangChonBV().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlbSum;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPDF;
    private javax.swing.JButton btnSum;
    private javax.swing.JButton btnTK;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbNgaylap;
    private javax.swing.JTable tblTK;
    private javax.swing.JTextField txtMaBC;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtND;
    private javax.swing.JTextField txtNgayBD;
    private javax.swing.JTextField txtNgayKT;
    // End of variables declaration//GEN-END:variables
}
