/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.CongTy;

import javax.swing.JOptionPane;
import model.CongTy;
import service.CongTyService;

/**
 *
 * @author nampr
 */
public class ThemCTy extends javax.swing.JFrame {
    CongTyService congtyService;
    CongTy congty;
    /**
     * Creates new form ThemGa
     */
    public ThemCTy() {
        initComponents();
        this.setLocationRelativeTo(null);
        congtyService = new CongTyService();
        congty = new CongTy();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSDT = new javax.swing.JTextField();
        txtWeb = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbMaGa = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaCTy = new javax.swing.JTextField();
        txtTenCTy = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EMETRO - TRANG THÊM CÔNG TY TÀU CAO TỐC");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSDT.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(txtSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, 258, 40));

        txtWeb.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(txtWeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 258, 40));

        btnThem.setBackground(new java.awt.Color(52, 152, 219));
        btnThem.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        getContentPane().add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, 130, 40));

        btnHuy.setBackground(new java.awt.Color(52, 152, 219));
        btnHuy.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setText("Huỷ bỏ");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });
        getContentPane().add(btnHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 540, 130, 40));

        jLabel5.setBackground(new java.awt.Color(52, 152, 219));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("THÊM THÔNG TIN CÔNG TY TÀU CAO TỐC");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 88));

        jLabel3.setBackground(new java.awt.Color(52, 152, 219));
        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("  Số điện thoại");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 140, 40));

        jLabel4.setBackground(new java.awt.Color(52, 152, 219));
        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("  Địa chỉ web");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 140, 40));

        lbMaGa.setBackground(new java.awt.Color(52, 152, 219));
        lbMaGa.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lbMaGa.setForeground(new java.awt.Color(255, 255, 255));
        lbMaGa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbMaGa.setText("  Mã công ty");
        lbMaGa.setOpaque(true);
        getContentPane().add(lbMaGa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 140, 40));

        jLabel2.setBackground(new java.awt.Color(52, 152, 219));
        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("  Tên công ty");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 140, 40));

        txtMaCTy.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(txtMaCTy, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 258, 40));

        txtTenCTy.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(txtTenCTy, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 258, 40));

        txtDiaChi.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(txtDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 258, 40));

        jLabel6.setBackground(new java.awt.Color(52, 152, 219));
        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("  Địa chỉ công ty");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 140, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/emetro7.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        /*String maga, tenga, ttga, vitri; */
        congty.setMaCTy(txtMaCTy.getText());
        congty.setTenCTy(txtTenCTy.getText());
        congty.setDCWeb(txtWeb.getText());
        congty.setDiaChi(txtDiaChi.getText());
        congty.setSDT(txtSDT.getText());

        congtyService.ThemCongTy(congty);

        JOptionPane.showMessageDialog(rootPane,"Thêm thành công !!");
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnThem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lbMaGa;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtMaCTy;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenCTy;
    private javax.swing.JTextField txtWeb;
    // End of variables declaration//GEN-END:variables
}
