/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.KSV;

import controller.ConnectionSQLServer;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author nampr
 */
public class TrangKSV extends javax.swing.JFrame {
    Connection cn = null;
    ResultSet rs = null;
    CallableStatement stored_pro = null;
    String loaive;
    /**
     * Creates new form TrangKSV
     */
    public TrangKSV() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public void LayLoaiVe(String MaVe){
        try {
            cn = ConnectionSQLServer.getConnectionDB();
            String sql = "SELECT LOAI_VE FROM VE WHERE MA_VE = ?";
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.setString(1, MaVe);
            rs = pst.executeQuery();
            
            if(rs.next()){
                loaive = rs.getString("LOAI_VE");
                
            }
        } catch (Exception e) {
        }
    }
    
    public void KtraVeThuong(String MaVe){
        try {
            cn = ConnectionSQLServer.getConnectionDB();
            stored_pro = cn.prepareCall("{call PROC_TT_VETHUONG(?)}");
            stored_pro.setString(1, MaVe);
            rs = stored_pro.executeQuery();
            System.out.println(rs);
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "OK!");
                rs.close();
                stored_pro.close();
                cn.close(); 
            }
        } catch (Exception e) {
        }
    }
    
    public void KtraVeThang(String MaVe){
        try {
            cn = ConnectionSQLServer.getConnectionDB();
            stored_pro = cn.prepareCall("{call PROC_TT_VETHANG(?)}");
            stored_pro.setString(1, MaVe);
            rs = stored_pro.executeQuery();
            System.out.println(rs);
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "OK!");
                rs.close();
                stored_pro.close();
                cn.close(); 
            }
        } catch (Exception e) {
        }
    }
    
    public void NhapTDSD(String MaVe){
        try {
            cn = ConnectionSQLServer.getConnectionDB();
            String sql = "INSERT INTO THOI_DIEM_SU_DUNG(MA_VE, NGAY) VALUES (?, ?)";
            PreparedStatement pst = cn.prepareStatement(sql); 
            pst.setString(1, MaVe);
            pst.setDate(2, Date.valueOf(LocalDate.now()));
            int result =  pst.executeUpdate();
            System.out.println(result);
        } catch (Exception e) {
        }
    }
    
    public void InTTVeThuong(String MaVe){
        try {
            cn = ConnectionSQLServer.getConnectionDB();
            String sql = "  SELECT TINH_TRANG_VE FROM VE_THUONG WHERE MA_VE = ?";
            PreparedStatement pst = cn.prepareStatement(sql); 
            pst.setString(1, MaVe);
            rs = pst.executeQuery();
            
            if(rs.next()){
                String ttve = rs.getString("TINH_TRANG_VE");
                System.out.println(ttve);
                txtTTVe.setText(ttve);
            }
        } catch (Exception e) {
        }
    }
    
    public void InTTVeThang(String MaVe){
        try {
            cn = ConnectionSQLServer.getConnectionDB();
            String sql = "  SELECT TINH_TRANG_VE FROM VE_THANG WHERE MA_VE = ?";
            PreparedStatement pst = cn.prepareStatement(sql); 
            pst.setString(1, MaVe);
            rs = pst.executeQuery();
            
            if(rs.next()){
                String ttve = rs.getString("TINH_TRANG_VE");
                System.out.println(ttve);
                txtTTVe.setText(ttve);
            }
        } catch (Exception e) {
        }
    }
    
    public void CapNhatTDVeThuong(String MaVe){
        try {
            cn = ConnectionSQLServer.getConnectionDB();
            String sql="UPDATE VE_THUONG SET THOI_DIEM_DUNG_VE = ? WHERE MA_VE= ? ";
           
            PreparedStatement pst = cn.prepareStatement(sql);
            
            pst.setDate(1, Date.valueOf(LocalDate.now()));  
            pst.setString(2, MaVe);
            int rs1= pst.executeUpdate();
            System.out.println(rs1); 
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMave = new javax.swing.JTextField();
        btnKtra = new javax.swing.JButton();
        txtTTVe = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnXacNhan = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EMETRO - TRANG CỔNG KIỂM SOÁT VÉ ");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtMave.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtMave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaveActionPerformed(evt);
            }
        });
        getContentPane().add(txtMave, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 233, -1));

        btnKtra.setBackground(new java.awt.Color(52, 152, 219));
        btnKtra.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnKtra.setForeground(new java.awt.Color(255, 255, 255));
        btnKtra.setText("Kiểm tra");
        btnKtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKtraActionPerformed(evt);
            }
        });
        getContentPane().add(btnKtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 130, 40));

        txtTTVe.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        getContentPane().add(txtTTVe, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 233, -1));

        jLabel1.setBackground(new java.awt.Color(52, 152, 219));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CỔNG KIỂM SOÁT VÉ TỰ ĐỘNG");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 67));

        jLabel2.setBackground(new java.awt.Color(52, 152, 219));
        jLabel2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("  Nhập mã vé để kiểm tra tình trạng vé của bạn");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 520, -1));

        jLabel3.setBackground(new java.awt.Color(52, 152, 219));
        jLabel3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("  Mã vé");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 172, 36));

        jLabel4.setBackground(new java.awt.Color(52, 152, 219));
        jLabel4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("  Tình trạng vé");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 172, 36));

        btnXacNhan.setBackground(new java.awt.Color(52, 152, 219));
        btnXacNhan.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btnXacNhan.setForeground(new java.awt.Color(255, 255, 255));
        btnXacNhan.setText("Xác nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });
        getContentPane().add(btnXacNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/emetro10.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 13, 640, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKtraActionPerformed
        // TODO add your handling code here:
        LayLoaiVe(txtMave.getText());
        System.out.println(loaive);
        if("Vé Thường".equals(loaive)){
            KtraVeThuong(txtMave.getText());
            InTTVeThuong(txtMave.getText());
        }
        if("Vé Tháng".equals(loaive)){
            NhapTDSD(txtMave.getText());
            KtraVeThang(txtMave.getText());
            InTTVeThang(txtMave.getText());
        }
    }//GEN-LAST:event_btnKtraActionPerformed

    private void txtMaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaveActionPerformed

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        // TODO add your handling code here:
        LayLoaiVe(txtMave.getText());
        if("Vé Thường".equals(loaive)){
            CapNhatTDVeThuong(txtMave.getText());
            KtraVeThuong(txtMave.getText());
            JOptionPane.showMessageDialog(rootPane, "Xác nhận vé thành công!");
        }
        this.dispose();
        new TrangKSV().setVisible(true);
    }//GEN-LAST:event_btnXacNhanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKtra;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtMave;
    private javax.swing.JTextField txtTTVe;
    // End of variables declaration//GEN-END:variables
}
