/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.TuyenTau;

import javax.swing.JOptionPane;
import model.TuyenTau;
import service.TuyenTauService;

/**
 *
 * @author nampr
 */
public class SuaTT extends javax.swing.JFrame {
    private TuyenTau tuyentau;
    TuyenTauService ttService;
    /**
     * Creates new form sua
     */
    public SuaTT(String maTT) {
        ttService = new TuyenTauService();
        tuyentau = ttService.getTTById(maTT);
        initComponents();
        this.setLocationRelativeTo(null);
        
        txtMatuyen.setText(tuyentau.getMaTT());
        txtTentuyen.setText(tuyentau.getTenTT());
        txtMacty.setText(tuyentau.getMaCty());
        txtGaxp.setText(tuyentau.getGaBD());
        txtGacuoi.setText(tuyentau.getGaCuoi());
        txtLoaituyen.setText(tuyentau.getLoaiTuyen());
        txtGiave.setText(tuyentau.getGiaTuyen());
        txtTinhtrang.setText(tuyentau.getTinhTrang());
        txtTgbd.setText(tuyentau.getTGbatdau());
        txtTgkt.setText(tuyentau.getTGkethuc());
        txtTgcho.setText(tuyentau.getTGcho());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSua = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtMatuyen = new javax.swing.JTextField();
        txtTentuyen = new javax.swing.JTextField();
        txtMacty = new javax.swing.JTextField();
        txtGaxp = new javax.swing.JTextField();
        txtGacuoi = new javax.swing.JTextField();
        txtLoaituyen = new javax.swing.JTextField();
        txtGiave = new javax.swing.JTextField();
        txtTinhtrang = new javax.swing.JTextField();
        txtTgbd = new javax.swing.JTextField();
        txtTgkt = new javax.swing.JTextField();
        txtTgcho = new javax.swing.JTextField();
        btnHuy = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TRANG SỬA TUYẾN TÀU CAO TỐC");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSua.setBackground(new java.awt.Color(52, 152, 219));
        btnSua.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setText("Lưu");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 790, 140, -1));

        jLabel13.setBackground(new java.awt.Color(52, 152, 219));
        jLabel13.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("SỬA THÔNG TIN TUYẾN TÀU CAO TỐC");
        jLabel13.setOpaque(true);
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 75));

        txtMatuyen.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtMatuyen.setEnabled(false);
        txtMatuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMatuyenActionPerformed(evt);
            }
        });
        getContentPane().add(txtMatuyen, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 400, 38));

        txtTentuyen.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtTentuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTentuyenActionPerformed(evt);
            }
        });
        getContentPane().add(txtTentuyen, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 400, 38));

        txtMacty.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(txtMacty, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 400, 38));

        txtGaxp.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(txtGaxp, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 400, 38));

        txtGacuoi.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(txtGacuoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 400, 38));

        txtLoaituyen.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(txtLoaituyen, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 400, 38));

        txtGiave.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(txtGiave, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, 400, 38));

        txtTinhtrang.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(txtTinhtrang, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 550, 400, 38));

        txtTgbd.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(txtTgbd, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 610, 400, 38));

        txtTgkt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(txtTgkt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 670, 400, 38));

        txtTgcho.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(txtTgcho, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 730, 400, 37));

        btnHuy.setBackground(new java.awt.Color(52, 152, 219));
        btnHuy.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setText("Huỷ bỏ");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });
        getContentPane().add(btnHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 790, 140, 40));

        jLabel12.setBackground(new java.awt.Color(52, 152, 219));
        jLabel12.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("  TG chờ");
        jLabel12.setOpaque(true);
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 730, 130, 40));

        jLabel11.setBackground(new java.awt.Color(52, 152, 219));
        jLabel11.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("  TG kết thúc");
        jLabel11.setOpaque(true);
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 670, 130, 40));

        jLabel10.setBackground(new java.awt.Color(52, 152, 219));
        jLabel10.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("  TG bắt đầu");
        jLabel10.setOpaque(true);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 610, 130, 40));

        jLabel9.setBackground(new java.awt.Color(52, 152, 219));
        jLabel9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("  Tình trạng");
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, 130, 40));

        jLabel8.setBackground(new java.awt.Color(52, 152, 219));
        jLabel8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("  Giá vé");
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 130, 40));

        jLabel7.setBackground(new java.awt.Color(52, 152, 219));
        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("  Loại tuyến");
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 130, 40));

        jLabel6.setBackground(new java.awt.Color(52, 152, 219));
        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("  Ga cuối");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 130, 40));

        jLabel4.setBackground(new java.awt.Color(52, 152, 219));
        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("  Ga xuất phát");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 130, 40));

        jLabel3.setBackground(new java.awt.Color(52, 152, 219));
        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("  Mã công ty");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 130, 40));

        jLabel2.setBackground(new java.awt.Color(52, 152, 219));
        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("  Tên tuyến");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 130, 40));

        jLabel1.setBackground(new java.awt.Color(52, 152, 219));
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("  Mã tuyến");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 130, 40));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/emetro_img123.jpg"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -90, 700, 980));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        tuyentau.setTenTT(txtTentuyen.getText());
        tuyentau.setMaCty(txtMacty.getText());
        tuyentau.setGaBD(txtGaxp.getText());
        tuyentau.setGaCuoi(txtGacuoi.getText());
        tuyentau.setLoaiTuyen(txtLoaituyen.getText());
        tuyentau.setGiaTuyen(txtGiave.getText());
        tuyentau.setTinhTrang(txtTinhtrang.getText());
        tuyentau.setTGbatdau(txtTgbd.getText());
        tuyentau.setTGkethuc(txtTgkt.getText());
        tuyentau.setTGcho(txtTgcho.getText());
        ttService.updateTT(tuyentau);

        JOptionPane.showMessageDialog(rootPane, "Sửa thành công!");

        this.dispose();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void txtMatuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMatuyenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMatuyenActionPerformed

    private void txtTentuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTentuyenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTentuyenActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnHuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnSua;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtGacuoi;
    private javax.swing.JTextField txtGaxp;
    private javax.swing.JTextField txtGiave;
    private javax.swing.JTextField txtLoaituyen;
    private javax.swing.JTextField txtMacty;
    private javax.swing.JTextField txtMatuyen;
    private javax.swing.JTextField txtTentuyen;
    private javax.swing.JTextField txtTgbd;
    private javax.swing.JTextField txtTgcho;
    private javax.swing.JTextField txtTgkt;
    private javax.swing.JTextField txtTinhtrang;
    // End of variables declaration//GEN-END:variables
}
