/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.TuyenTau;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.TuyenTau;
import service.TuyenTauService;

/**
 *
 * @author nampr
 */
public class TrangQLTT extends javax.swing.JFrame {
    private List<TuyenTau> tuyentaus;
    TuyenTauService ttService;
    DefaultTableModel tblModel;
    private String macty;
    /**
     * Creates new form TrangChu
     * @param MaCTy
     */
    public TrangQLTT(String MaCTy) {
        initComponents();
        this.setLocationRelativeTo(null);
        macty = MaCTy;
        ttService = new TuyenTauService();
        
        tblModel = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        
        tableTT.setModel(tblModel);
        
        tblModel.addColumn("Mã tuyến tàu");
        tblModel.addColumn("Tên tuyến tàu");
        tblModel.addColumn("Mã công ty");
        tblModel.addColumn("Ga xuất phát");
        tblModel.addColumn("Ga cuối");
        tblModel.addColumn("Loại tuyến");
        tblModel.addColumn("Giá vé");
        tblModel.addColumn("Tình trạng");
        tblModel.addColumn("TG bắt đầu");
        tblModel.addColumn("TG kết thúc");
        tblModel.addColumn("TG chờ");
        
        setTableData(ttService.getAllTTs(MaCTy));
        
    }
    
    private void setTableData(List<TuyenTau> tuyentaus){
        for (TuyenTau tuyentau: tuyentaus){
            tblModel.addRow(new Object[]{tuyentau.getMaTT(), tuyentau.getTenTT(), tuyentau.getMaCty(), tuyentau.getGaBD(), tuyentau.getGaCuoi(), tuyentau.getLoaiTuyen(), tuyentau.getGiaTuyen(), tuyentau.getTinhTrang(), tuyentau.getTGbatdau(), tuyentau.getTGkethuc(), tuyentau.getTGcho()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableTT = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnTra = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnGTG = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EMETRO - TRANG QUẢN LÝ TUYẾN TÀU CAO TỐC");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableTT.setBackground(new java.awt.Color(255, 255, 255));
        tableTT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã tuyến ", "Tên tuyến", "Mã công ty", "Ga xuất phát", "Ga cuối", "Loại tuyến", "Giá vé", "Tình trạng", "TG bắt đầu", "TG kết thúc", "Tg chờ"
            }
        ));
        tableTT.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tableTT);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 951, 345));

        btnRefresh.setBackground(new java.awt.Color(52, 152, 219));
        btnRefresh.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("REFRESH");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 130, -1, 50));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnThem.setBackground(new java.awt.Color(205, 248, 241));
        btnThem.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnThem.setForeground(new java.awt.Color(0, 0, 0));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(205, 248, 241));
        btnSua.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnSua.setForeground(new java.awt.Color(0, 0, 0));
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(52, 152, 219));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HOẠT ĐỘNG");
        jLabel1.setOpaque(true);

        btnTra.setBackground(new java.awt.Color(205, 248, 241));
        btnTra.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnTra.setForeground(new java.awt.Color(0, 0, 0));
        btnTra.setText("Tra cứu");
        btnTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTra, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnThem)
                .addGap(35, 35, 35)
                .addComponent(btnTra)
                .addGap(34, 34, 34)
                .addComponent(btnSua)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, 340));

        btnThoat.setBackground(new java.awt.Color(52, 152, 219));
        btnThoat.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnThoat.setForeground(new java.awt.Color(255, 255, 255));
        btnThoat.setText("THOÁT");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        getContentPane().add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 570, 120, 50));

        jLabel2.setBackground(new java.awt.Color(52, 152, 219));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("QUẢN LÝ THÔNG TIN TUYẾN TÀU CAO TỐC");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 100));

        btnGTG.setBackground(new java.awt.Color(52, 152, 219));
        btnGTG.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnGTG.setForeground(new java.awt.Color(255, 255, 255));
        btnGTG.setText("Xét Ga Trung Gian");
        btnGTG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGTGActionPerformed(evt);
            }
        });
        getContentPane().add(btnGTG, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 130, -1, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/emetro8.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1350, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        tblModel.setRowCount(0);
        System.out.println(macty);
        setTableData(ttService.getAllTTs(macty));
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        new ThemTT().setVisible(true);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        int selectedIndex = tableTT.getSelectedRow();
        if (selectedIndex == -1){
            JOptionPane.showMessageDialog(TrangQLTT.this, "Vui lòng chọn tuyến tàu cần sửa!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            String maTT = String.valueOf(tableTT.getValueAt(selectedIndex, 0));
            new SuaTT(maTT).setVisible(true);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraActionPerformed
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog(this, "Nhập tên tuyến tàu cần tra cứu:");
        if(input != null && input.length() > 0){
            tuyentaus = ttService.findTTByTenTT(macty, input);
            tblModel.setRowCount(0);
            setTableData(tuyentaus);
        } else{
            tblModel.setRowCount(0);
            setTableData(ttService.getAllTTs(macty));
        }
    }//GEN-LAST:event_btnTraActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        int resConfirmDialog = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát không?", "XÁC NHẬN", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (resConfirmDialog == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnGTGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGTGActionPerformed
        // TODO add your handling code here:
        int selectedIndex = tableTT.getSelectedRow();
        if (selectedIndex == -1){
            JOptionPane.showMessageDialog(TrangQLTT.this, "Vui lòng chọn tuyến tàu!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            String MaTT = String.valueOf(tableTT.getValueAt(selectedIndex, 0));
            new TrangGaTrungGian(MaTT).setVisible(true);
        }
    }//GEN-LAST:event_btnGTGActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGTG;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableTT;
    // End of variables declaration//GEN-END:variables
}
